name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update && apt-get upgrade -y && sudo apt install -y build-essential curl
        curl -LsS https://r.mariadb.com/downloads/mariadb_repo_setup | sudo bash
        sudo apt-get update && sudo apt install -y libmariadb-dev libmariadb3
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f ./app/requirements.txt ]; then pip install -r ./app/requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
